apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-pvc 
  namespace: dokuwiki 
spec:
  template:
    spec:
      containers:
      - name: snapshot-to-pvc
        image: quay.io/rcook/tools:kubectl
        command: ["/bin/bash","/mover/transfer.sh"]
        env:
        - name: DESTINATION
          value: database
        - name: PVC_NAME
          value: dokuwiki 
        - name: SIZE
          value: 3Gi
        volumeMounts:
        - name: transfer-volume
          mountPath: /mover
      serviceAccount: transfer
      volumes:
        - name: transfer-volume
          configMap:
            name: transfer
      restartPolicy: Never
  backoffLimit: 4
