---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dokuwiki
  name: dokuwiki
  namespace: dokuwiki
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30007
  selector:
    app.kubernetes.io/name: dokuwiki
