apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dokuwiki 
  name: snapshot-changer
rules:
- apiGroups:
  - scribe.backube
  resources:
  - replicationdestinations
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
