---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: database-destination
  namespace: dokuwiki-pvc 
spec:
  trigger:
    schedule: "*/5 * * * *"
  rclone:
    rcloneConfigSection: "aws-s3-bucket"
    rcloneDestPath: "rcook-backup"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot 
    accessModes: [ReadWriteOnce]
    capacity: 8Gi
    volumeSnapshotClassName: csi-hostpath-snapclass
