apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: dokuwiki
  name: dokuwiki-service
spec:
  port:
    targetPort: 80
  to:
    kind: ""
    name: dokuwiki-service
    weight: null
status: {}
