apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: dokuwiki
    app.kubernetes.io/part-of: dokuwiki
  name: dokuwiki-deployment
spec:
  port:
    targetPort: port-1
  to:
    kind: ""
    name: dokuwiki-deployment
    weight: null
status: {}
